name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  REACT_APP_FB_API_KEY: ${{ secrets.REACT_APP_FB_API_KEY }}
  REACT_APP_FB_APP_ID: ${{ secrets.REACT_APP_FB_APP_ID }}
  REACT_APP_FB_AUTH_DOMAIN: ${{ secrets.REACT_APP_FB_AUTH_DOMAIN }}
  REACT_APP_FB_DB_URL: ${{ secrets.REACT_APP_FB_DB_URL }}
  REACT_APP_FB_MSG_ID: ${{ secrets.REACT_APP_FB_MSG_ID }}
  REACT_APP_FB_PJ_ID: ${{ secrets.REACT_APP_FB_PJ_ID }}
  REACT_APP_FB_STORE: ${{ secrets.REACT_APP_FB_STORE }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: CI=true yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
